/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-secondary-container": "#004666",
        "on-surface-variant": "#464555",
        "surface-tint": "#4d44e3",
        "on-primary": "#ffffff",
        "tertiary-container": "#a44100",
        "on-primary-fixed-variant": "#3323cc",
        "on-error-container": "#93000a",
        "tertiary": "#7e3000",
        "inverse-on-surface": "#f3f0f2",
        "on-primary-fixed": "#0f0069",
        "primary": "#3525cd",
        "on-primary-container": "#dad7ff",
        "surface-variant": "#e5e1e4",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#ffd2be",
        "secondary-fixed": "#c9e6ff",
        "secondary-container": "#39b8fd",
        "background": "#fcf8fb",
        "surface": "#fcf8fb",
        "surface-container": "#f0edf0",
        "tertiary-fixed": "#ffdbcc",
        "error": "#ba1a1a",
        "primary-fixed": "#e2dfff",
        "on-tertiary-fixed": "#351000",
        "surface-container-high": "#eae7ea",
        "primary-container": "#4f46e5",
        "surface-container-low": "#f6f2f5",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#004c6e",
        "surface-dim": "#dcd9dc",
        "outline": "#777587",
        "inverse-surface": "#313032",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1c1b1d",
        "on-tertiary": "#ffffff",
        "on-background": "#1c1b1d",
        "primary-fixed-dim": "#c3c0ff",
        "surface-container-highest": "#e5e1e4",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#001e2f",
        "inverse-primary": "#c3c0ff",
        "secondary-fixed-dim": "#89ceff",
        "tertiary-fixed-dim": "#ffb695",
        "on-tertiary-fixed-variant": "#7b2f00",
        "surface-bright": "#fcf8fb",
        "outline-variant": "#c7c4d8",
        "secondary": "#006591"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "space-md": "0.875rem",
        "space-lg": "1.25rem",
        "gutter": "1rem",
        "space-xl": "2rem",
        "margin": "1.5rem",
        "margin-desktop": "2.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "gutter-desktop": "1.5rem"
      },
      "fontFamily": {
        "headline-sm": ["Geist"],
        "body-md": ["Geist"],
        "headline-md": ["Geist"],
        "headline-xl-mobile": ["Geist"],
        "label-md": ["Geist"],
        "code-sm": ["JetBrains Mono"],
        "body-sm": ["Geist"],
        "headline-lg": ["Geist"],
        "headline-xl": ["Geist"],
        "body-lg": ["Geist"],
        "label-sm": ["Geist"]
      },
      "fontSize": {
        "headline-sm": ["15px", { "lineHeight": "22px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["13px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-md": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "headline-xl-mobile": ["26px", { "lineHeight": "34px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "-0.005em", "fontWeight": "500" }],
        "code-sm": ["12px", { "lineHeight": "18px", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "18px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.025em", "fontWeight": "600" }],
        "body-lg": ["15px", { "lineHeight": "24px", "letterSpacing": "-0.005em", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }]
      }
    }
  },
  plugins: [],
}
